[package]
name = "toycpip"
version = "0.1.0"
edition = "2024"

[dependencies]
pnet = "0.35.0"
thiserror = "2.0.12"
log = "0.4"
env_logger = "0.11.8"
clap = { version = "4.5.40", features = ["derive"] }
